[package]
name = "layer-proc-gen"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-tree = "0.4.0"


[dependencies]
tracing = "0.1.40"
