name: Continuous deployment
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # build wasm blob and prep dist dir
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo build --release --target wasm32-unknown-unknown --example infinite_roads
      - run: cp target/wasm32-unknown-unknown/release/examples/infinite_roads.wasm dist/infinite_roads.wasm

      # deploy to gh pages
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
